# Generated by Django 5.2.4 on 2025-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_sign",
            field=models.BooleanField(default=False),
        ),
    ]
