# Generated by Django 5.2.4 on 2025-08-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="publication_sign",
            new_name="is_published",
        ),
    ]
